language: python
dist: xenial
sudo: required
cache:
- apt
addons:
  apt:
    packages:
    - nginx
    - curl
    - wget
    - ruby
    - ruby-dev
install:
- sudo gem install inspec
- sudo curl -sL -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
- sudo unzip -d /usr/local/bin /tmp/terraform.zip
- sudo gem install bundler
- bundle install
script:
- terraform fmt
- terraform init
- kitchen converge
- kitchen verify
- kitchen destroy
env:
  secure: GLMha1ScoItFxrbNH9Bcn58XCC2AX6qIEJ/Q+QTEYAvtkIxtx9V6OpSdx6IRWike+xbyikEe/+kZaubiXiwhLZrtg8cyoRzSYfYqovdwvfgrj+979slFoxjjcLYmhj38JvPsyrmhDwpMv3fPBhozXUpgOUzxTgu0EBE9PrAaow+eDr5+Iy5UOPG5Q3JVKXJlWKo6exk5BxM+z9Kv9wqYo9BpbZWMbYP+VL2ulwyG5kc0UHixXUkc5K5JjNs5AZt01thGdPDUDvu/ix8iqlrbtZpwvB/1/4eTTqWklj6W/fNXgiV0YRT+MhC1sR9vX4UNFDCL/aw1AFTQFo+/TFg2sfAM674V8sgDDClYzI9CR9Y/ACA3ZJoKrp1tZslSgIjQM5vxc8XHZ7QqXpuYoKMEmnvhq/xs5ZBS0SOU0USoZZqBJ/f0JMnYcCnvTjAHDzMIfnjihvfcTkXecFn3mblPqVa4ny97UkpmY2zSJfbN5E91nQgD48AHhvjG6BAMScDeyvzkgGubF4sb7kSMY3opbnAj7xdBZSSvlSXgqnqec5ZXjbbSlgP/1DFyqW3sGcIXJQ5uNQTw0D2FC1HFqPfeCVet3EeiBdBwTGc/Tw8IUHkfEScSdr9+9rd1GQO4bSnauOJIYNPdlTTrVNQ6pcOWPrybSW0VZlegNRe0/NoVi+Y=
